server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 196.168.182.128:1111 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'